filebeat.inputs:
  - type: log
    paths:
      - "/var/log/suricata/*.log"
      - "/opt/zeek/logs/current/*.log"

output.elasticsearch:
  hosts: ["https://localhost:9200"]
  username: "filebeat_internal"
  password: "pass"
  ssl:
    enabled: true
    certificate_authorities: ["/opt/elasticsearch-8.17.3/config/certs/http_ca.crt"]

  ssl.verification_mode: none

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
