# ================== Kibana Configuration ==================

# ---------------------- Server Settings ----------------------

server.port: 5601
server.host: "127.0.0.1"

# Enable TLS for Kibana (Secures the web interface)
server.ssl.enabled: true
server.ssl.certificate: "/opt/elasticsearch-8.17.3/config/certs/kibana/kibana.crt"
server.ssl.key: "/opt/elasticsearch-8.17.3/config/certs/kibana/kibana.key"

# ---------------------- Elasticsearch Connection ----------------------

elasticsearch.hosts: ["https://127.0.0.1:9200"]
elasticsearch.username: "kibana_system"
elasticsearch.password: "pass"

# ---------------------- TLS Settings for Elasticsearch ----------------------

elasticsearch.ssl.certificateAuthorities: ["/opt/elasticsearch-8.17.3/config/certs/ca/ca.crt"]
elasticsearch.ssl.verificationMode: certificate  # Use "certificate" for security; "none" only for testing

# ---------------------- Security and Encryption ----------------------

xpack.security.encryptionKey: ".."
xpack.encryptedSavedObjects.encryptionKey: ".."
xpack.reporting.encryptionKey: ".."
xpack.fleet.enabled: false
